version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_DOCKER: '1'
    volumes:
      - ".:/usr/src/app"
    networks:
      - checkup
    depends_on:
      - couchdb
  couchdb:
    image: "couchdb:latest"
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - "checkupcouchdb:/opt/couchdb/data"
    networks:
      - checkup
networks:
  checkup:
    driver: bridge
volumes:
  checkupcouchdb:
    driver: local
