export const tracheostomyValues = [
  "Suction canister no more than full and cleaned daily",
  "Check suction pressure working at 125mmHg",
  "Correct size suction catheters available and stocked.",
  "Ambu-bag available and working (if applicable)",
  "Sterile water for humidifier available and humidifier working",
  "Humidifier circuit changes weekly - record date",
  "Tracheostomy tape secured and changed",
  "Tracheostomy site cleaned, and dressing changed",
  "Swedish nose changed daily (if applicable)",
  "Oximeter working & sats probe position  changed 4 hourly (if applicable)",
  "Nebuliser Pot cleaned & set change due - Record date (DD/MM/YYYY) (changed weekly)",
  "Oximeter checked and more than 1/4 in tank",
  "Emergency tracheostomy kit available (1x tracheostomy same size, 1x smaller size, lubricant, suction catheters, gloves, dressing, trachy tapes/ties)",
];
